// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";

function Nav(Props) {
  var handleClick = React.useCallback((function (path) {
          RescriptReactRouter.push(path);
        }), []);
  return React.createElement("nav", {
              className: "flex justify-center space-x-2 w-full mx-auto"
            }, React.createElement("button", {
                  className: "bg-blue-300 p-2 mx-1 rounded text-white",
                  onClick: (function (param) {
                      handleClick("cat");
                    })
                }, "cat"), React.createElement("button", {
                  className: "bg-blue-300 p-2 mx-1 rounded text-white",
                  onClick: (function (param) {
                      handleClick("dog");
                    })
                }, "dog"));
}

var make = Nav;

export {
  make ,
}
/* react Not a pure module */
